# Filename rados-config.yml
version: 0.1
log:
  level: debug
  fields:
    sevice: registry
    environment: development
storage:
  cache:
    layerinfo: inmemory
  rados:
    poolname: radospool
    username: radosuser
    chunksize: 4194304
  maintenance:
    uploadpurging:
    	enabled: false
http:
  addr: :5000
  secret:  asecretforlocaldevelopment
  debug:
    addr: localhost:5001
